@startuml
title NewCrossoverOperatorAdaptiveShuffle.crossover(p1, p2)
start
if (p1.fitness <= p2.fitness?) then (да)
  :best = p1;
  :worst = p2;
else (нет)
  :best = p2;
  :worst = p1;
endif

:g1 = [];
:g2 = [];

:для каждого (gb, gw) из zip(best.genes, worst.genes);
while (есть следующий ген?) is (да)
  :diff = abs(gb - gw);
  :shuffle_prob = min(1.0, diff * shuffle_strength);

  if (random() < shuffle_prob?) then (да)
    if (random() < 0.5?) then (да)
      :g1 += gw;
      :g2 += gb;
    else (нет)
      :g1 += gb;
      :g2 += gw;
    endif
  else (нет)
    :prob_best = 0.5 + bias_strength;

    if (random() < prob_best?) then (да)
      :g1 += gb;
    else (нет)
      :g1 += gw;
    endif

    if (random() < prob_best?) then (да)
      :g2 += gb;
    else (нет)
      :g2 += gw;
    endif
  endif
endwhile (нет)

:return [Individual(g1), Individual(g2)];
stop
@enduml
